language: android

android:
  components:
    - tools
    - platform-tools

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

jdk:
  - oraclejdk8

script:
  - ./gradlew test

notifications:
  email: false

sudo: false